name: Test

on:
    push:

jobs:
    test:
        name: Test
        runs-on: 'ubuntu-latest'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Build packages
              run: npm run build

            - name: Run tests
              run: npm run test
