name: TypeScript

on:
    push:

jobs:
    typescript:
        name: TypeScript
        runs-on: 'ubuntu-latest'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Build packages
              run: npm run build

            - name: Run TypeScript
              run: npm run typescript
